source 'https://rubygems.org'

gem 'activerecord'

group :development, :test do
  gem 'rspec'
  gem 'rr'
  gem 'rake'

  # factory_girl for fixtures:
  gem 'factory_girl'
  gem 'database_cleaner'

  gem 'sqlite3'
end
